PETMADCalculator._model was renamed to model
Failing test: https://github.com/lab-cosmo/atomistic-cookbook/actions/runs/20653474546/job/59302044938#step:5:2231
> AttributeError: 'PETMADCalculator' object has no attribute '_model'

Upstream definition of `PETMADCalculator.model`:
https://github.com/lab-cosmo/pet-mad/blob/12e970981cd45b805d7aadc524a2009aa52f4cf3/src/pet_mad/calculator.py#L125